// <auto-generated />
namespace Onboarding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class price_annotation2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(price_annotation2));
        
        string IMigrationMetadata.Id
        {
            get { return "201812042120177_price_annotation2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
