// <auto-generated />
namespace Onboarding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sale_annotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sale_annotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201812042141066_sale_annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
